-- Generated by GmodSoundGen

-- Sound: 11
sound.Add({
	name = "mw2_m4_fire",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100},
	sound = {
		"mw2_m4/fire/Wpn_M4A1_Fire_01.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_02.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_03.ogg"
		}
})

sound.Add({
	name = "mw2_m4_fire_ads",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {110},
	sound = {
		"mw2_m4/fire/Wpn_M4A1_Fire_01.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_02.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_03.ogg"
		}
})

sound.Add({
	name = "mw2_m4_fire_s",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100},
	sound = {
		"mw2_m4/fire/Wpn_M4A1_Fire_Sup_01.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_Sup_02.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_Sup_03.ogg"
		}
})

sound.Add({
	name = "mw2_m4_fire_s_ads",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {110},
	sound = {
		"mw2_m4/fire/Wpn_M4A1_Fire_Sup_01.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_Sup_02.ogg",
		"mw2_m4/fire/Wpn_M4A1_Fire_Sup_03.ogg"
		}
})

--9mm

sound.Add({
	name = "mw2_m4_9mm_fire",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100},
	sound = {
		"mw2_m4/fire/weap_mpapa5_fire_plr_shot_01.ogg",
		"mw2_m4/fire/weap_mpapa5_fire_plr_shot_02.ogg",
		"mw2_m4/fire/weap_mpapa5_fire_plr_shot_03.ogg"
		}
})

sound.Add({
	name = "mw2_m4_9mm_fire_ads",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {110},
	sound = {
		"mw2_m4/fire/weap_mpapa5_fire_plr_shot_01.ogg",
		"mw2_m4/fire/weap_mpapa5_fire_plr_shot_02.ogg",
		"mw2_m4/fire/weap_mpapa5_fire_plr_shot_03.ogg"
		}
})

--DM
sound.Add({
	name = "mw2_m4dm_fire",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100},
	sound = {
		"mw2_m4/fire/weap_acharlie300blk_fire_plr_shot_01.ogg",
		"mw2_m4/fire/weap_acharlie300blk_fire_plr_shot_02.ogg",
		"mw2_m4/fire/weap_acharlie300blk_fire_plr_shot_03.ogg"
		}
})

sound.Add({
	name = "mw2_m4dm_fire_ads",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {105},
	sound = {
		"mw2_m4/fire/weap_acharlie300blk_fire_plr_shot_01.ogg",
		"mw2_m4/fire/weap_acharlie300blk_fire_plr_shot_02.ogg",
		"mw2_m4/fire/weap_acharlie300blk_fire_plr_shot_03.ogg"
		}
})
--

-----混响

sound.Add({
	name = "mw2_m4_fire_atom",
    channel =        CHAN_WEAPON,
    volume =      0.5,
	sound = {
		"mw2_m4/fire/ext/weap_ar10_fire_plr_atmo_ext1_01.ogg", --10
		"mw2_m4/fire/ext/weap_ar10_fire_plr_atmo_ext1_02.ogg",
		"mw2_m4/fire/ext/weap_ar10_fire_plr_atmo_ext1_03.ogg"
		}
})

sound.Add({
	name = "mw2_m4_fire_atom_s",
    channel =        CHAN_REFLECTION,
    volume =      0.15,
	sound = {
		"mw2_m4/fire/ext/weap_ar10_fire_plr_atmo_ext1_01.ogg",
		"mw2_m4/fire/ext/weap_ar10_fire_plr_atmo_ext1_02.ogg",
		"mw2_m4/fire/ext/weap_ar10_fire_plr_atmo_ext1_03.ogg"
		}
})

-----

sound.Add({
    name =           "wfoly_ar_mike4_ads_down",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/wfoly_ar_mike4_ads_down.ogg"}
})

sound.Add({
    name =           "wfoly_ar_mike4_ads_up",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/wfoly_ar_mike4_ads_up.ogg"}
})

sound.Add({
    name =           "wpn_br_hcharlie36_plr_last_mech_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/wpn_br_hcharlie36_plr_last_mech_01.ogg"}
})

-----

sound.Add({
    name =           "wfoly_plr_ar_mike4_drop_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_drop.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_raise_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_raise.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_selectsemi_off_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_selectsemi_off.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_selectsemi_on_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_selectsemi_on.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_04",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_charge.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_return.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_07",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_mvt2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_08",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_mvt2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_03",
    channel =        CHAN_WEAPON + 3,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_04",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_mvt3.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_05",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_rack.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_07",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_08",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_charge.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_09",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_handle.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_10",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_mvt4.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_11",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_04",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_chargehand.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_06",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_return.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_07",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_assist.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmag_08",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmag_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_02",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_mvt2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_04",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_mvt3.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_charge.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_mvt4.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_07",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_08",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_lockback.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_09",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_return.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_empty_xmag_10",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_empty_xmag_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmaglrg_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmaglrg_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmaglrg_02",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmaglrg_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_inspect_xmaglrg_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_inspect_xmaglrg_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_shoulder.ogg"}
})

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_03",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_mvt2.ogg"}
-- })

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_04",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_06",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_07",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_mvt3.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_08",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_shoulder2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_grab.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_04",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_maghit.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_05",
    channel =        CHAN_WEAPON + 3,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_mvt2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_07",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_bolt.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_08",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_fast_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_fast_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_fast_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_fast_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_fast_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_fast_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_fast_04",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_fast_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_fast_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_fast_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_fast_01",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_fast_02",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_mag_rel.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_fast_03",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_maghit.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_fast_04",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_fast_05",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_bolt.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_fast_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_shoulder.ogg"}
})

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmag_01",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmag_magcatch.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmag_02",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmag_magout.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmag_03",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmag_turn.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmag_04",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmag_maghit.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmag_05",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmag_magin.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmag_06",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmag_shoulder.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmag_01",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmag_mvt1.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmag_02",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmag_magout.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmag_03",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmag_maghit.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmag_04",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmag_magin.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmag_05",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmag_bolt.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmag_06",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmag_shoulder.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmaglrg_01",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmaglrg_mvt1.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmaglrg_02",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmaglrg_magout.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmaglrg_03",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmaglrg_mvt2.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmaglrg_04",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmaglrg_maghit.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmaglrg_05",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmaglrg_magin.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_fast_xmaglrg_06",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_fast_xmaglrg_shoulder.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmaglrg_01",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmaglrg_magout.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmaglrg_02",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmaglrg_mvt1.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmaglrg_03",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmaglrg_mvt2.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmaglrg_04",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmaglrg_maghit.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmaglrg_05",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmaglrg_magin.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmaglrg_06",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmaglrg_bolt.ogg"}
-- })

-- sound.Add({
    -- name =           "wfoly_plr_ar_mike4_reload_empty_fast_xmaglrg_07",
    -- channel =        CHAN_WEAPON + 1,
    -- volume =         1,
    -- sound =          {"mw2_m4/p01_ar_mike4_reload_empty_fast_xmaglrg_shoulder.ogg"}
-- })

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_bodyhit.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_magcatch.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_04",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_maghit.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_06",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_07",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_mvt2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_08",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmag_09",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmag_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_02",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_04",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_maghit.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_05",
    channel =        CHAN_WEAPON + 3,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_mvt2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_07",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_bolt.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmag_08",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmag_shoulder.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmaglrg_01",
    channel =        CHAN_WEAPON + 2,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmaglrg_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmaglrg_02",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmaglrg_shoulder1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmaglrg_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmaglrg_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmaglrg_04",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmaglrg_maghit.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmaglrg_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmaglrg_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmaglrg_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmaglrg_mvt2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_xmaglrg_07",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_xmaglrg_shoulder2.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmaglrg_01",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmaglrg_over.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmaglrg_02",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmaglrg_magout.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmaglrg_03",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmaglrg_mvt1.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmaglrg_04",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmaglrg_magbump.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmaglrg_05",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmaglrg_magin.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmaglrg_06",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmaglrg_bolt.ogg"}
})

sound.Add({
    name =           "wfoly_plr_ar_mike4_reload_empty_xmaglrg_07",
    channel =        CHAN_WEAPON + 1,
    volume =         1,
    sound =          {"mw2_m4/p01_ar_mike4_reload_empty_xmaglrg_shoulder.ogg"}
})

